### ISSUE TITLE
Compile script dependency

### ISSUE THREAD

**Issue by EkkiBrue** [karnkaul/rpi4-install-vulkan#3]
I´getting an error with the most recent build of Raspberry OS 64 bit fully apt updated.

Could you please help to get this right ?

```
meson.build:1609:0: ERROR: Invalid version of dependency, need 'libdrm' ['>=2.4.109'] found '2.4.104'.

A full log can be found at /home/pi/mesa/build/release/meson-logs/meson-log.txt
```

[meson-log.txt](https://github.com/karnkaul/rpi4-install-vulkan/files/8321575/meson-log.txt)

**Comment by karnkaul** [comment]
That's a shame. Unfortunately the error is from within the driver's build scripts. The best suggestion I can't think of is to try to somehow install `libdrm 2.4.109` or newer.
