### ISSUE TITLE
libdrm-dev version 2.4.109 seems to be required ?

### ISSUE THREAD

**Issue by James2022-rgb** [karnkaul/rpi4-install-vulkan#4]
I just wanted to note that `meson` failed complaining that `libdrm-nouveau` version `2.4.109` was required, when only `2.4.104` was available with `sudo apt-get install libdrm-dev`.

Indeed, `apt-cache madison libdrm-dev` returns:
```
libdrm-dev | 2.4.104-1+rpi1 | http://raspbian.raspberrypi.org/raspbian bullseye/main armhf Packages
```

I needed to manually build and install `libdrm-dev` version `2.4.110` from source.

After that, this script worked like a charm. Thanks !

**Comment by James2022-rgb** [comment]
Just noticed this problem was mentioned in #3 🤦‍♂️.

I was able to proceed with the instruction found at [libdrm-2.4.110](https://www.linuxfromscratch.org/blfs/view/svn/x/libdrm.html) from "Beyond Linux® From Scratch",
(minus the `--prefix=$XORG_PREFIX` bit).

It would be nice if this process was somehow automated, but if it's not trivial to solve in the general case,
it might be nice to have the fact documented somewhere that the latest version of `libdrm-dev` may be needed.

**Comment by karnkaul** [comment]
Thanks for documenting the fix/workaround, @James2022-rgb! Given the comprehensive details here, I've just linked your comment in the README directly. 🙏
